fix: ClipPPOLoss args in coding_ppo.py
the main two params foreseen in ClipPPOLoss are named "actor" and "critic", respectively.
Without them, the following error will be raised during the script run:
"TypeError: ClipPPOLoss.__init__() missing 2 required positional arguments: 'actor' and 'critic'".